#!/usr/bin/env python3
"""Optional, explicit Coop setup for Linux x86_64 and capable WSL 2 hosts.

No dependencies beyond Python 3.10+. Importing this module has no side effects.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
from pathlib import Path
import platform
import re
import shutil
import stat
import subprocess
import sys
import tarfile
import urllib.request

VERSION = "v0.6.0"
ARCHIVE = f"coop-{VERSION}-x86_64-unknown-linux-musl.tar.gz"
ARCHIVE_SHA256 = "fced8803bfe655a9614cae3338b03cbfaf46eff959c31d15a34f0ad87ca67700"
DOWNLOAD_URL = f"https://github.com/trailofbits/coop/releases/download/{VERSION}/{ARCHIVE}"
MAX_DOWNLOAD = 100 * 1024 * 1024
SAFE_PATH = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"


class SetupError(Exception):
    pass


def host_home() -> Path:
    # Do not let inherited HOME select another user's credentials/configuration.
    import pwd
    return Path(pwd.getpwuid(os.getuid()).pw_dir)


def install_root() -> Path:
    return host_home() / ".local/share/gpt-helper-coop" / VERSION


def clean_environment(root: Path) -> dict[str, str]:
    import pwd
    account = pwd.getpwuid(os.getuid())
    return {
        "HOME": account.pw_dir,
        "USER": account.pw_name,
        "LOGNAME": account.pw_name,
        "PATH": str(root / "bin") + ":" + SAFE_PATH,
        "LANG": "C.UTF-8",
    }


def config_text(root: Path) -> str:
    data = root / "data"
    quote = lambda value: json.dumps(str(value), ensure_ascii=False)
    return f'''# Generated by GPT Helper. No host tokens or agent configuration.
data_dir = {quote(data)}
firecracker_bin = {quote(data / "firecracker")}
github = "off"

[vm]
kernel_path = {quote(data / "vmlinux")}
vcpu_count = 2
mem_size_mib = 4096
template_size_gib = 8

[setup]
prompt_for_pat = false

[claude]
config_dir = false
env_forward = []
marketplaces = []
plugins = []

[codex]
config_dir = false
env_forward = []
marketplaces = []
plugins = []

[updates]
mode = "off"
'''


def require_platform() -> None:
    if platform.system() != "Linux" or platform.machine().lower() not in ("x86_64", "amd64"):
        raise SetupError("This package supports Linux x86_64 only (including WSL 2 with working KVM).")


def require_kvm() -> None:
    import fcntl
    try:
        with open("/dev/kvm", "rb+", buffering=0) as device:
            if not stat.S_ISCHR(os.fstat(device.fileno()).st_mode):
                raise SetupError("/dev/kvm is not a character device.")
            if fcntl.ioctl(device.fileno(), 0xAE00, 0) != 12:  # KVM_GET_API_VERSION
                raise SetupError("KVM API is unavailable or incompatible.")
    except OSError as error:
        raise SetupError(f"Working, accessible KVM is required; no host fallback: {error}") from error


def download_archive() -> bytes:
    # No inherited proxy settings, GitHub login, cookies or authorization headers.
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    request = urllib.request.Request(DOWNLOAD_URL, headers={"User-Agent": "GPT-Helper-Coop-Setup"})
    with opener.open(request, timeout=60) as response:
        if not response.geturl().startswith("https://"):
            raise SetupError("Refusing a non-HTTPS download.")
        payload = response.read(MAX_DOWNLOAD + 1)
    if len(payload) > MAX_DOWNLOAD:
        raise SetupError("Release download exceeded the size limit.")
    if hashlib.sha256(payload).hexdigest() != ARCHIVE_SHA256:
        raise SetupError("Coop archive SHA-256 mismatch; nothing installed.")
    return payload


def release_binaries(payload: bytes) -> dict[str, bytes]:
    """Read regular release files only; never extract archive-controlled paths."""
    binaries = {}
    prefix = ARCHIVE.removesuffix(".tar.gz") + "/"
    with tarfile.open(fileobj=io.BytesIO(payload), mode="r:gz") as archive:
        for member in archive.getmembers():
            if not member.name.startswith(prefix):
                continue
            name = member.name[len(prefix):]
            if name not in ("coop", "coop-proxy", "LICENSE"):
                continue
            if name in binaries or not member.isfile() or not 0 < member.size <= MAX_DOWNLOAD:
                raise SetupError(f"Invalid binary member: {name}")
            stream = archive.extractfile(member)
            if stream is None:
                raise SetupError(f"Cannot read binary: {name}")
            binaries[name] = stream.read(MAX_DOWNLOAD + 1)
    if set(binaries) != {"coop", "coop-proxy", "LICENSE"}:
        raise SetupError("Release archive is missing expected regular binaries or LICENSE.")
    return binaries


def install(root: Path) -> None:
    if root.exists() or root.is_symlink():
        raise SetupError(f"Installation already exists; it will not be overwritten: {root}")
    binaries = release_binaries(download_archive())
    root.mkdir(parents=True, mode=0o700, exist_ok=False)
    (root / "bin").mkdir(mode=0o700)
    for name, content in binaries.items():
        target = root / name if name == "LICENSE" else root / "bin" / name
        with target.open("xb") as output:
            output.write(content)
        target.chmod(0o600 if name == "LICENSE" else 0o700)
    (root / "config.toml").write_text(config_text(root), encoding="utf-8")
    manifest = {"version": VERSION, "archive_sha256": ARCHIVE_SHA256,
                "binaries": {name: hashlib.sha256(data).hexdigest() for name, data in binaries.items()}}
    (root / "installation.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"Installed {VERSION} with verified SHA-256 in {root}. No VM created or started.")


def verify_installation(root: Path) -> None:
    if (root / "config.toml").read_text(encoding="utf-8") != config_text(root):
        raise SetupError("Configuration differs from the restricted template; refusing to run.")
    manifest = json.loads((root / "installation.json").read_text(encoding="utf-8"))
    if manifest.get("version") != VERSION or manifest.get("archive_sha256") != ARCHIVE_SHA256:
        raise SetupError("Installation does not match this helper's pinned release.")
    for name in ("coop", "coop-proxy"):
        binary = root / "bin" / name
        if binary.is_symlink() or not binary.is_file():
            raise SetupError(f"Missing regular binary: {name}")
        if hashlib.sha256(binary.read_bytes()).hexdigest() != manifest.get("binaries", {}).get(name):
            raise SetupError(f"Installed binary checksum mismatch: {name}")


def run_coop(root: Path, arguments: list[str], capture: bool = False) -> str:
    result = subprocess.run(
        [str(root / "bin/coop"), "--config", str(root / "config.toml"), *arguments],
        env=clean_environment(root), cwd=str(root), check=True,
        text=True, stdout=subprocess.PIPE if capture else None,
    )
    return result.stdout or ""


def check_capabilities(root: Path) -> None:
    for command, flags in {
        "up": ["--copy", "--no-agents", "--no-prompt", "--no-devcontainer", "--exclude-git", "--new-instance"],
        "setup": ["--no-devcontainer"],
    }.items():
        help_text = run_coop(root, [command, "--help"], capture=True)
        for flag in flags:
            if flag not in help_text:
                raise SetupError(f"Required flag missing: {command} {flag}; no weaker fallback.")


def project_path(value: str, root: Path) -> Path:
    selected = Path(value).expanduser()
    if selected.is_symlink():
        raise SetupError("Select a real, reviewed project directory, not a symlink.")
    project = selected.resolve(strict=True)
    if not project.is_dir():
        raise SetupError("Project must be a directory.")
    home = host_home().resolve()
    if project == Path(project.anchor) or project == home or project in home.parents:
        raise SetupError("Refusing a root/home directory or an ancestor of the home directory.")
    if len(project.parts) < 3 or re.fullmatch(r"/mnt/[a-z](?:/Users(?:/[^/]+)?)?", project.as_posix()):
        raise SetupError("Refusing a broad system directory, drive root or Windows user home.")
    if project == root or project in root.parents or root in project.parents:
        raise SetupError("Project and Coop state must be separate directories.")
    # Reject obvious secret-bearing inputs. This is not an exhaustive secret scanner.
    blocked = {".env", ".ssh", ".aws", ".azure", ".kube", ".gnupg", ".codex", ".claude"}
    def unreadable(error: OSError) -> None:
        raise SetupError(f"Cannot inspect project entry: {error}") from error
    for directory, folders, files in os.walk(project, followlinks=False, onerror=unreadable):
        folders[:] = [name for name in folders if name != ".git"]
        for name in folders + files:
            path = Path(directory) / name
            if path.is_symlink() or name in blocked or name.endswith((".pem", ".key")) or name.startswith(".env."):
                raise SetupError(f"Use a reviewed, sanitized project copy; refused entry: {path}")
    return project


def instance_name(value: str) -> str:
    if not re.fullmatch(r"[a-z][a-z0-9-]{0,39}", value):
        raise argparse.ArgumentTypeError("Use 1-40 lowercase letters/digits/hyphens, starting with a letter.")
    return value


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="action", required=True)
    for action in ("install", "setup", "up", "exec", "stop", "check", "status"):
        command = sub.add_parser(action)
        if action in ("install", "setup", "up", "exec", "stop"):
            command.add_argument("--confirm", action="store_true", help="Confirm this scoped operation; not standing agent permission.")
        if action in ("up", "exec", "stop"):
            command.add_argument("--name", required=True, type=instance_name)
        if action == "up":
            command.add_argument("--project", required=True, help="Reviewed Linux path; on WSL use /mnt/c/... if needed.")
        if action == "exec":
            command.add_argument("command", nargs=argparse.REMAINDER)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        if hasattr(args, "confirm") and not args.confirm:
            raise SetupError("Explicit --confirm required. Agents must first obtain task-scoped user permission.")
        require_platform()
        root = install_root()
        if args.action == "install":
            install(root)
            return 0
        verify_installation(root)
        if args.action == "status":
            run_coop(root, ["list", "--json"])
            return 0
        if args.action == "stop":
            run_coop(root, ["stop", args.name])
            return 0
        require_kvm()
        check_capabilities(root)
        if args.action == "check":
            missing = [name for name in ("sudo", "curl", "tar", "mkfs.ext4", "resize2fs") if not shutil.which(name, path=SAFE_PATH)]
            if missing:
                raise SetupError("Missing host prerequisites: " + ", ".join(missing))
            print("Binary/config checks and KVM API passed. VM boot and networking are not tested.")
        elif args.action == "setup":
            run_coop(root, ["setup", "--no-devcontainer"])
        elif args.action == "up":
            project = project_path(args.project, root)
            instances = json.loads(run_coop(root, ["list", "--json"], capture=True))
            if any(item["name"] == args.name for item in instances):
                raise SetupError("Name already exists; refusing to reuse a potentially modified VM. Choose a fresh name.")
            run_coop(root, ["up", str(project), "--name", args.name, "--new-instance", "--copy", "--no-agents", "--no-prompt", "--no-devcontainer", "--exclude-git"])
            run_coop(root, ["exec", args.name, "--", "/usr/bin/true"])
            print("Guest command succeeded; VM is reachable. Project code has not been run.")
        elif args.action == "exec":
            command = args.command[1:] if args.command[:1] == ["--"] else args.command
            if not command:
                raise SetupError("Specify a guest command after --.")
            run_coop(root, ["exec", args.name, "--", "/usr/bin/true"])
            run_coop(root, ["exec", args.name, "--", *command])
        return 0
    except subprocess.CalledProcessError as error:
        print(f"Coop command failed (exit {error.returncode}); no host fallback.", file=sys.stderr)
        return error.returncode if 0 < error.returncode < 126 else 1
    except (SetupError, OSError, ValueError, tarfile.TarError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
